server:
  port: 9000
  servlet:
    context-path: /tgh/
  
spring:
  datasource:
    platform: postgres
    driverclassname: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devdb
    username: postgres
    password: p@tchw0rd
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true 
        format_sql: true
        ddl-auto: create
        temp:
          use_jdbc_metadata_defaults: false 

logging:
  level:
    root: INFO
    org:
      springframework: DEBUG